data:
  target: main.DataModuleFromConfig  # Use the pure PyTorch version from main.py
  params:
    batch_size: 64  # Smaller batch size (was 64)
    num_workers: 2  # Fewer workers (was 12)
    wrap: false
    train:
      target: ldm.data.imagenet.ImageNetTrain
      params:
        data_root: /datasets/ilsvrc/current/
        config:
          size: 128  # Smaller image size (was 256)
    validation:
      target: ldm.data.imagenet.ImageNetValidation
      params:
        data_root: /datasets/ilsvrc/current/
        config:
          size: 128  # Smaller image size (was 256)

training:
  epochs: 100
  seed: 42
  accumulate_grad_batches: 1
  checkpoint_frequency: 10
  log_frequency: 10
  train: true
  no_test: false
  scale_lr: true
  debug: false

logging:
  logdir: logs
  name: ""
  resume: ""
  postfix: ""

wandb:
  entity: sar-diffusion
  project: simple-vae-testing
  name: test-run
  enabled: true

# Model configuration will be loaded from the specific config file
model:
  base_learning_rate: 1.0e-4 