model:
  base_learning_rate: 4.5e-6
  target: ldm.models.autoencoder.VQModelInterface
  params:
    embed_dim: 4
    n_embed: 8192  # Smaller codebook for testing
    ddconfig:
      double_z: false
      z_channels: 4
      resolution: 128  # Smaller resolution for testing
      in_channels: 3
      out_ch: 3
      ch: 64  # Smaller base channels
      ch_mult: [1, 2, 2, 4]  # num_down = len(ch_mult)-1
      num_res_blocks: 1  # Fewer res blocks
      attn_resolutions: [16]  # Adjusted for smaller resolution
      dropout: 0.0
    lossconfig:
      target: torch.nn.Identity

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8  # Smaller batch size
    wrap: false
    train:
      target: ldm.data.imagenet.ImageNetTrain
      params:
        config:
          size: 128  # Smaller image size
    validation:
      target: ldm.data.imagenet.ImageNetValidation
      params:
        config:
          size: 128  # Smaller image size